from trading_algos.algorithmspec import AlertAlgorithmSpec, register_algorithm
from trading_algos.alertgen.algorithms.factor_risk_premia.dividend_yield_strategy import (
    build_dividend_yield_strategy,
)
from trading_algos.alertgen.algorithms.factor_risk_premia.growth_factor_strategy import (
    build_growth_factor_strategy,
)
from trading_algos.alertgen.algorithms.factor_risk_premia.liquidity_factor_strategy import (
    build_liquidity_factor_strategy,
)
from trading_algos.alertgen.algorithms.factor_risk_premia.low_beta_betting_against_beta import (
    build_low_beta_betting_against_beta,
)
from trading_algos.alertgen.algorithms.factor_risk_premia.low_volatility_strategy import (
    build_low_volatility_strategy,
)
from trading_algos.alertgen.core.validation import require_factor_portfolio_param


def register_factor_risk_premia_alert_algorithms() -> None:
    specs = [
        AlertAlgorithmSpec(
            key="low_volatility_strategy",
            name="Low Volatility Strategy",
            catalog_ref="algorithm:100",
            builder=build_low_volatility_strategy,
            default_param={
                "rows": [],
                "field_names": ["volatility_20d", "realized_volatility"],
                "rebalance_frequency": "monthly",
                "top_n": 2,
                "bottom_n": 0,
                "long_only": True,
                "minimum_universe_size": 2,
            },
            param_normalizer=require_factor_portfolio_param,
            description="Rank assets by lower realized volatility and build a rebalance-driven portfolio.",
            param_schema=(
                {
                    "key": "rows",
                    "label": "Rows",
                    "type": "object_list",
                    "required": True,
                    "description": "Panel rows containing ts, symbol, close, and factor fields.",
                },
                {
                    "key": "field_names",
                    "label": "Field names",
                    "type": "string_list",
                    "required": True,
                    "description": "Factor fields used to compute the low-volatility score.",
                },
                {
                    "key": "rebalance_frequency",
                    "label": "Rebalance frequency",
                    "type": "string",
                    "required": True,
                    "enum": ["monthly", "weekly", "all"],
                    "description": "Schedule used to sample rebalance dates.",
                },
                {
                    "key": "top_n",
                    "label": "Top N",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Number of strongest ranked assets to allocate to.",
                },
                {
                    "key": "bottom_n",
                    "label": "Bottom N",
                    "type": "integer",
                    "required": False,
                    "minimum": 0,
                    "description": "Optional number of weakest assets to short when long_only is false.",
                },
                {
                    "key": "long_only",
                    "label": "Long only",
                    "type": "boolean",
                    "required": True,
                    "description": "Whether the portfolio allocates only to long positions.",
                },
                {
                    "key": "minimum_universe_size",
                    "label": "Minimum universe size",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Minimum number of scored assets required before the rebalance is actionable.",
                },
            ),
            tags=("factor", "low_volatility", "rebalance"),
            category="factor_risk_premia",
            family="factor_risk_premia",
            subcategory="low",
            warmup_period=1,
            input_domains=("fundamentals_pti", "multi_asset_panel"),
            asset_scope="portfolio",
            output_modes=("ranking", "selection", "weights", "diagnostics"),
        ),
        AlertAlgorithmSpec(
            key="low_beta_betting_against_beta",
            name="Low Beta / Betting-Against-Beta",
            catalog_ref="algorithm:103",
            builder=build_low_beta_betting_against_beta,
            default_param={
                "rows": [],
                "field_names": ["beta_252d", "market_beta"],
                "rebalance_frequency": "monthly",
                "top_n": 2,
                "bottom_n": 0,
                "long_only": True,
                "minimum_universe_size": 2,
            },
            param_normalizer=require_factor_portfolio_param,
            description="Prefer lower-beta securities and allocate on rebalance dates.",
            param_schema=(
                {
                    "key": "rows",
                    "label": "Rows",
                    "type": "object_list",
                    "required": True,
                    "description": "Panel rows containing ts, symbol, close, and factor fields.",
                },
                {
                    "key": "field_names",
                    "label": "Field names",
                    "type": "string_list",
                    "required": True,
                    "description": "Factor fields used to compute the beta score.",
                },
                {
                    "key": "rebalance_frequency",
                    "label": "Rebalance frequency",
                    "type": "string",
                    "required": True,
                    "enum": ["monthly", "weekly", "all"],
                    "description": "Schedule used to sample rebalance dates.",
                },
                {
                    "key": "top_n",
                    "label": "Top N",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Number of strongest ranked assets to allocate to.",
                },
                {
                    "key": "bottom_n",
                    "label": "Bottom N",
                    "type": "integer",
                    "required": False,
                    "minimum": 0,
                    "description": "Optional number of weakest assets to short when long_only is false.",
                },
                {
                    "key": "long_only",
                    "label": "Long only",
                    "type": "boolean",
                    "required": True,
                    "description": "Whether the portfolio allocates only to long positions.",
                },
                {
                    "key": "minimum_universe_size",
                    "label": "Minimum universe size",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Minimum number of scored assets required before the rebalance is actionable.",
                },
            ),
            tags=("factor", "beta", "rebalance"),
            category="factor_risk_premia",
            family="factor_risk_premia",
            subcategory="low",
            warmup_period=1,
            input_domains=("fundamentals_pti", "multi_asset_panel"),
            asset_scope="portfolio",
            output_modes=("ranking", "selection", "weights", "diagnostics"),
        ),
        AlertAlgorithmSpec(
            key="dividend_yield_strategy",
            name="Dividend Yield Strategy",
            catalog_ref="algorithm:107",
            builder=build_dividend_yield_strategy,
            default_param={
                "rows": [],
                "field_names": ["dividend_yield", "forward_dividend_yield"],
                "rebalance_frequency": "monthly",
                "top_n": 2,
                "bottom_n": 0,
                "long_only": True,
                "minimum_universe_size": 2,
            },
            param_normalizer=require_factor_portfolio_param,
            description="Rank assets by dividend yield and build an income-oriented factor portfolio.",
            param_schema=(
                {
                    "key": "rows",
                    "label": "Rows",
                    "type": "object_list",
                    "required": True,
                    "description": "Panel rows containing ts, symbol, close, and factor fields.",
                },
                {
                    "key": "field_names",
                    "label": "Field names",
                    "type": "string_list",
                    "required": True,
                    "description": "Factor fields used to compute the dividend-yield score.",
                },
                {
                    "key": "rebalance_frequency",
                    "label": "Rebalance frequency",
                    "type": "string",
                    "required": True,
                    "enum": ["monthly", "weekly", "all"],
                    "description": "Schedule used to sample rebalance dates.",
                },
                {
                    "key": "top_n",
                    "label": "Top N",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Number of strongest ranked assets to allocate to.",
                },
                {
                    "key": "bottom_n",
                    "label": "Bottom N",
                    "type": "integer",
                    "required": False,
                    "minimum": 0,
                    "description": "Optional number of weakest assets to short when long_only is false.",
                },
                {
                    "key": "long_only",
                    "label": "Long only",
                    "type": "boolean",
                    "required": True,
                    "description": "Whether the portfolio allocates only to long positions.",
                },
                {
                    "key": "minimum_universe_size",
                    "label": "Minimum universe size",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Minimum number of scored assets required before the rebalance is actionable.",
                },
            ),
            tags=("factor", "dividend", "rebalance"),
            category="factor_risk_premia",
            family="factor_risk_premia",
            subcategory="dividend",
            warmup_period=1,
            input_domains=("fundamentals_pti", "multi_asset_panel"),
            asset_scope="portfolio",
            output_modes=("ranking", "selection", "weights", "diagnostics"),
        ),
        AlertAlgorithmSpec(
            key="growth_factor_strategy",
            name="Growth Factor Strategy",
            catalog_ref="algorithm:108",
            builder=build_growth_factor_strategy,
            default_param={
                "rows": [],
                "field_names": ["earnings_growth", "sales_growth"],
                "rebalance_frequency": "monthly",
                "top_n": 2,
                "bottom_n": 0,
                "long_only": True,
                "minimum_universe_size": 2,
            },
            param_normalizer=require_factor_portfolio_param,
            description="Rank assets by growth metrics and allocate to the strongest names on rebalance dates.",
            param_schema=(
                {
                    "key": "rows",
                    "label": "Rows",
                    "type": "object_list",
                    "required": True,
                    "description": "Panel rows containing ts, symbol, close, and factor fields.",
                },
                {
                    "key": "field_names",
                    "label": "Field names",
                    "type": "string_list",
                    "required": True,
                    "description": "Factor fields used to compute the growth score.",
                },
                {
                    "key": "rebalance_frequency",
                    "label": "Rebalance frequency",
                    "type": "string",
                    "required": True,
                    "enum": ["monthly", "weekly", "all"],
                    "description": "Schedule used to sample rebalance dates.",
                },
                {
                    "key": "top_n",
                    "label": "Top N",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Number of strongest ranked assets to allocate to.",
                },
                {
                    "key": "bottom_n",
                    "label": "Bottom N",
                    "type": "integer",
                    "required": False,
                    "minimum": 0,
                    "description": "Optional number of weakest assets to short when long_only is false.",
                },
                {
                    "key": "long_only",
                    "label": "Long only",
                    "type": "boolean",
                    "required": True,
                    "description": "Whether the portfolio allocates only to long positions.",
                },
                {
                    "key": "minimum_universe_size",
                    "label": "Minimum universe size",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Minimum number of scored assets required before the rebalance is actionable.",
                },
            ),
            tags=("factor", "growth", "rebalance"),
            category="factor_risk_premia",
            family="factor_risk_premia",
            subcategory="growth",
            warmup_period=1,
            input_domains=("fundamentals_pti", "multi_asset_panel"),
            asset_scope="portfolio",
            output_modes=("ranking", "selection", "weights", "diagnostics"),
        ),
        AlertAlgorithmSpec(
            key="liquidity_factor_strategy",
            name="Liquidity Factor Strategy",
            catalog_ref="algorithm:109",
            builder=build_liquidity_factor_strategy,
            default_param={
                "rows": [],
                "field_names": ["liquidity_score", "turnover_ratio"],
                "rebalance_frequency": "monthly",
                "top_n": 2,
                "bottom_n": 0,
                "long_only": True,
                "minimum_universe_size": 2,
            },
            param_normalizer=require_factor_portfolio_param,
            description="Rank assets by liquidity-related metrics and build a tradability-aware factor sleeve.",
            param_schema=(
                {
                    "key": "rows",
                    "label": "Rows",
                    "type": "object_list",
                    "required": True,
                    "description": "Panel rows containing ts, symbol, close, and factor fields.",
                },
                {
                    "key": "field_names",
                    "label": "Field names",
                    "type": "string_list",
                    "required": True,
                    "description": "Factor fields used to compute the liquidity score.",
                },
                {
                    "key": "rebalance_frequency",
                    "label": "Rebalance frequency",
                    "type": "string",
                    "required": True,
                    "enum": ["monthly", "weekly", "all"],
                    "description": "Schedule used to sample rebalance dates.",
                },
                {
                    "key": "top_n",
                    "label": "Top N",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Number of strongest ranked assets to allocate to.",
                },
                {
                    "key": "bottom_n",
                    "label": "Bottom N",
                    "type": "integer",
                    "required": False,
                    "minimum": 0,
                    "description": "Optional number of weakest assets to short when long_only is false.",
                },
                {
                    "key": "long_only",
                    "label": "Long only",
                    "type": "boolean",
                    "required": True,
                    "description": "Whether the portfolio allocates only to long positions.",
                },
                {
                    "key": "minimum_universe_size",
                    "label": "Minimum universe size",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Minimum number of scored assets required before the rebalance is actionable.",
                },
            ),
            tags=("factor", "liquidity", "rebalance"),
            category="factor_risk_premia",
            family="factor_risk_premia",
            subcategory="liquidity",
            warmup_period=1,
            input_domains=("fundamentals_pti", "multi_asset_panel"),
            asset_scope="portfolio",
            output_modes=("ranking", "selection", "weights", "diagnostics"),
        ),
    ]
    for spec in specs:
        register_algorithm(spec)
