from trading_algos.algorithmspec import AlertAlgorithmSpec, register_algorithm
from trading_algos.alertgen.algorithms.microstructure_hft.bid_ask_market_making import (
    build_bid_ask_market_making_algorithm,
)
from trading_algos.alertgen.algorithms.microstructure_hft.closing_auction_strategy import (
    build_closing_auction_strategy_algorithm,
)
from trading_algos.alertgen.algorithms.microstructure_hft.inventory_skewed_market_making import (
    build_inventory_skewed_market_making_algorithm,
)
from trading_algos.alertgen.algorithms.microstructure_hft.liquidity_rebate_capture import (
    build_liquidity_rebate_capture_algorithm,
)
from trading_algos.alertgen.algorithms.microstructure_hft.microprice_strategy import (
    build_microprice_strategy_algorithm,
)
from trading_algos.alertgen.algorithms.microstructure_hft.opening_auction_strategy import (
    build_opening_auction_strategy_algorithm,
)
from trading_algos.alertgen.algorithms.microstructure_hft.order_book_imbalance_strategy import (
    build_order_book_imbalance_strategy_algorithm,
)
from trading_algos.alertgen.algorithms.microstructure_hft.queue_position_strategy import (
    build_queue_position_strategy_algorithm,
)
from trading_algos.alertgen.core.validation import (
    require_bid_ask_market_making_param,
    require_inventory_skewed_market_making_param,
    require_order_book_imbalance_strategy_param,
    require_microprice_strategy_param,
    require_queue_position_strategy_param,
    require_liquidity_rebate_capture_param,
    require_opening_auction_strategy_param,
    require_closing_auction_strategy_param,
)


def register_microstructure_hft_alert_algorithms() -> None:
    specs = [
        AlertAlgorithmSpec(
            key="bid_ask_market_making",
            name="Bid-Ask Market Making",
            catalog_ref="algorithm:62",
            builder=build_bid_ask_market_making_algorithm,
            default_param={
                "rows": [],
                "own_order_rows": [],
                "min_spread": 0.01,
                "inventory_limit": 100.0,
            },
            param_normalizer=require_bid_ask_market_making_param,
            description="Prototype two-sided market-making scaffold with inventory-aware suppression.",
            category="microstructure_hft",
            family="microstructure_hft",
            subcategory="bid",
            warmup_period=1,
            input_domains=("order_book", "own_order_state"),
            output_modes=("quote_action", "signal", "diagnostics"),
            runtime_kind="streaming",
            asset_scope="single_asset",
            composition_roles=("execution_only",),
        ),
        AlertAlgorithmSpec(
            key="inventory_skewed_market_making",
            name="Inventory-Skewed Market Making",
            catalog_ref="algorithm:63",
            builder=build_inventory_skewed_market_making_algorithm,
            default_param={
                "rows": [],
                "own_order_rows": [],
                "inventory_target": 0.0,
                "skew_sensitivity": 1.0,
            },
            param_normalizer=require_inventory_skewed_market_making_param,
            description="Prototype inventory-skewed quote bias using own-order state.",
            category="microstructure_hft",
            family="microstructure_hft",
            subcategory="inventory",
            warmup_period=1,
            input_domains=("order_book", "own_order_state"),
            output_modes=("quote_action", "signal", "diagnostics"),
            runtime_kind="streaming",
            asset_scope="single_asset",
            composition_roles=("execution_only",),
        ),
        AlertAlgorithmSpec(
            key="order_book_imbalance_strategy",
            name="Order Book Imbalance Strategy",
            catalog_ref="algorithm:64",
            builder=build_order_book_imbalance_strategy_algorithm,
            default_param={
                "rows": [],
                "own_order_rows": [],
                "imbalance_threshold": 0.2,
            },
            param_normalizer=require_order_book_imbalance_strategy_param,
            description="Prototype directional signal from top-of-book imbalance.",
            category="microstructure_hft",
            family="microstructure_hft",
            subcategory="order",
            warmup_period=1,
            input_domains=("order_book", "own_order_state"),
            output_modes=("quote_action", "signal", "diagnostics"),
            runtime_kind="streaming",
            asset_scope="single_asset",
            composition_roles=("execution_only",),
        ),
        AlertAlgorithmSpec(
            key="microprice_strategy",
            name="Microprice Strategy",
            catalog_ref="algorithm:65",
            builder=build_microprice_strategy_algorithm,
            default_param={"rows": [], "own_order_rows": [], "edge_threshold": 0.005},
            param_normalizer=require_microprice_strategy_param,
            description="Prototype microprice edge signal over the current midprice.",
            category="microstructure_hft",
            family="microstructure_hft",
            subcategory="microprice",
            warmup_period=1,
            input_domains=("order_book", "own_order_state"),
            output_modes=("quote_action", "signal", "diagnostics"),
            runtime_kind="streaming",
            asset_scope="single_asset",
            composition_roles=("execution_only",),
        ),
        AlertAlgorithmSpec(
            key="queue_position_strategy",
            name="Queue Position Strategy",
            catalog_ref="algorithm:66",
            builder=build_queue_position_strategy_algorithm,
            default_param={
                "rows": [],
                "own_order_rows": [],
                "keep_threshold": 0.4,
                "cancel_threshold": 0.2,
            },
            param_normalizer=require_queue_position_strategy_param,
            description="Prototype queue-position keep/cancel signal from fill-probability estimates.",
            category="microstructure_hft",
            family="microstructure_hft",
            subcategory="queue",
            warmup_period=1,
            input_domains=("order_book", "own_order_state"),
            output_modes=("quote_action", "signal", "diagnostics"),
            runtime_kind="streaming",
            asset_scope="single_asset",
            composition_roles=("execution_only",),
        ),
        AlertAlgorithmSpec(
            key="liquidity_rebate_capture",
            name="Liquidity Rebate Capture",
            catalog_ref="algorithm:67",
            builder=build_liquidity_rebate_capture_algorithm,
            default_param={
                "rows": [],
                "own_order_rows": [],
                "maker_rebate": 0.002,
                "adverse_selection_buffer": 0.001,
            },
            param_normalizer=require_liquidity_rebate_capture_param,
            description="Prototype maker-rebate capture with adverse-selection guardrails.",
            category="microstructure_hft",
            family="microstructure_hft",
            subcategory="liquidity",
            warmup_period=1,
            input_domains=("order_book", "own_order_state"),
            output_modes=("quote_action", "signal", "diagnostics"),
            runtime_kind="streaming",
            asset_scope="single_asset",
            composition_roles=("execution_only",),
        ),
        AlertAlgorithmSpec(
            key="opening_auction_strategy",
            name="Opening Auction Strategy",
            catalog_ref="algorithm:68",
            builder=build_opening_auction_strategy_algorithm,
            default_param={"rows": [], "own_order_rows": [], "auction_threshold": 50.0},
            param_normalizer=require_opening_auction_strategy_param,
            description="Prototype opening-auction imbalance participation scaffold.",
            category="microstructure_hft",
            family="microstructure_hft",
            subcategory="opening",
            warmup_period=1,
            input_domains=("order_book", "own_order_state"),
            output_modes=("quote_action", "signal", "diagnostics"),
            runtime_kind="streaming",
            asset_scope="single_asset",
            composition_roles=("execution_only",),
        ),
        AlertAlgorithmSpec(
            key="closing_auction_strategy",
            name="Closing Auction Strategy",
            catalog_ref="algorithm:69",
            builder=build_closing_auction_strategy_algorithm,
            default_param={"rows": [], "own_order_rows": [], "auction_threshold": 50.0},
            param_normalizer=require_closing_auction_strategy_param,
            description="Prototype closing-auction imbalance participation scaffold.",
            category="microstructure_hft",
            family="microstructure_hft",
            subcategory="closing",
            warmup_period=1,
            input_domains=("order_book", "own_order_state"),
            output_modes=("quote_action", "signal", "diagnostics"),
            runtime_kind="streaming",
            asset_scope="single_asset",
            composition_roles=("execution_only",),
        ),
    ]
    for spec in specs:
        register_algorithm(spec)
