from trading_algos.algorithmspec import AlertAlgorithmSpec, register_algorithm
from trading_algos.alertgen.algorithms.volatility_options.atr_channel_breakout import (
    ATRChannelBreakoutAlertAlgorithm,
)
from trading_algos.alertgen.algorithms.volatility_options.delta_neutral_volatility_trading import (
    build_delta_neutral_volatility_trading_algorithm,
)
from trading_algos.alertgen.algorithms.volatility_options.dispersion_trading import (
    build_dispersion_trading_algorithm,
)
from trading_algos.alertgen.algorithms.volatility_options.gamma_scalping import (
    build_gamma_scalping_algorithm,
)
from trading_algos.alertgen.algorithms.volatility_options.skew_trading import (
    build_skew_trading_algorithm,
)
from trading_algos.alertgen.algorithms.volatility_options.straddle_breakout_timing import (
    build_straddle_breakout_timing_algorithm,
)
from trading_algos.alertgen.algorithms.volatility_options.term_structure_trading import (
    build_term_structure_trading_algorithm,
)
from trading_algos.alertgen.algorithms.volatility_options.volatility_breakout import (
    VolatilityBreakoutAlertAlgorithm,
)
from trading_algos.alertgen.algorithms.volatility_options.volatility_mean_reversion import (
    VolatilityMeanReversionAlertAlgorithm,
)
from trading_algos.alertgen.algorithms.volatility_options.volatility_risk_premium_capture import (
    build_volatility_risk_premium_capture_algorithm,
)
from trading_algos.alertgen.core.validation import (
    require_delta_neutral_volatility_trading_param,
    require_dispersion_trading_param,
    require_gamma_scalping_param,
    require_skew_trading_param,
    require_straddle_breakout_timing_param,
    require_term_structure_trading_param,
    require_atr_channel_breakout_param,
    require_volatility_breakout_param,
    require_volatility_mean_reversion_param,
    require_volatility_risk_premium_capture_param,
)


def _build_volatility_breakout(symbol, report_base_path, alg_param, **_kwargs):
    return VolatilityBreakoutAlertAlgorithm(
        symbol,
        report_base_path=report_base_path,
        atr_window=alg_param["atr_window"],
        compression_window=alg_param["compression_window"],
        compression_threshold=alg_param["compression_threshold"],
        breakout_lookback=alg_param["breakout_lookback"],
        breakout_buffer=alg_param["breakout_buffer"],
        confirmation_bars=alg_param["confirmation_bars"],
    )


def _build_atr_channel_breakout(symbol, report_base_path, alg_param, **_kwargs):
    return ATRChannelBreakoutAlertAlgorithm(
        symbol,
        report_base_path=report_base_path,
        channel_window=alg_param["channel_window"],
        atr_window=alg_param["atr_window"],
        atr_multiplier=alg_param["atr_multiplier"],
        confirmation_bars=alg_param["confirmation_bars"],
    )


def _build_volatility_mean_reversion(symbol, report_base_path, alg_param, **_kwargs):
    return VolatilityMeanReversionAlertAlgorithm(
        symbol,
        report_base_path=report_base_path,
        volatility_window=alg_param["volatility_window"],
        baseline_window=alg_param["baseline_window"],
        high_threshold=alg_param["high_threshold"],
        low_threshold=alg_param["low_threshold"],
        confirmation_bars=alg_param["confirmation_bars"],
    )


def register_volatility_options_alert_algorithms() -> None:
    specs = [
        AlertAlgorithmSpec(
            key="volatility_breakout",
            name="Volatility Breakout",
            catalog_ref="algorithm:52",
            builder=_build_volatility_breakout,
            default_param={
                "atr_window": 5,
                "compression_window": 5,
                "compression_threshold": 2.0,
                "breakout_lookback": 5,
                "breakout_buffer": 0.1,
                "confirmation_bars": 1,
            },
            param_normalizer=require_volatility_breakout_param,
            description="Trade upside breakouts after a compressed volatility regime expands.",
            param_schema=(
                {
                    "key": "atr_window",
                    "label": "ATR window",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Lookback used for average true range.",
                },
                {
                    "key": "compression_window",
                    "label": "Compression window",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Lookback used to measure rolling compression range.",
                },
                {
                    "key": "compression_threshold",
                    "label": "Compression threshold",
                    "type": "number",
                    "required": True,
                    "minimum": 0.0,
                    "description": "Maximum range-to-ATR ratio considered compressed.",
                },
                {
                    "key": "breakout_lookback",
                    "label": "Breakout lookback",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Lookback used to set the breakout reference high.",
                },
                {
                    "key": "breakout_buffer",
                    "label": "Breakout buffer",
                    "type": "number",
                    "required": True,
                    "minimum": 0.0,
                    "description": "Minimum price buffer above the breakout level.",
                },
                {
                    "key": "confirmation_bars",
                    "label": "Confirmation bars",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Consecutive breakout bars required before confirmation.",
                },
            ),
            tags=("volatility", "breakout", "compression"),
            category="volatility_options",
            family="volatility_options",
            subcategory="volatility",
            warmup_period=6,
            output_modes=("signal", "score", "confidence"),
        ),
        AlertAlgorithmSpec(
            key="atr_channel_breakout",
            name="ATR Channel Breakout",
            catalog_ref="algorithm:53",
            builder=_build_atr_channel_breakout,
            default_param={
                "channel_window": 5,
                "atr_window": 5,
                "atr_multiplier": 1.0,
                "confirmation_bars": 1,
            },
            param_normalizer=require_atr_channel_breakout_param,
            description="Break out when price closes beyond dynamic ATR-based channel bands.",
            param_schema=(
                {
                    "key": "channel_window",
                    "label": "Channel window",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Lookback used for the channel midpoint.",
                },
                {
                    "key": "atr_window",
                    "label": "ATR window",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Lookback used for average true range.",
                },
                {
                    "key": "atr_multiplier",
                    "label": "ATR multiplier",
                    "type": "number",
                    "required": True,
                    "minimum": 0.0,
                    "description": "ATR multiple used to widen channel bands.",
                },
                {
                    "key": "confirmation_bars",
                    "label": "Confirmation bars",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Consecutive channel breaks required before confirmation.",
                },
            ),
            tags=("volatility", "atr", "channel"),
            category="volatility_options",
            family="volatility_options",
            subcategory="atr",
            warmup_period=5,
            output_modes=("signal", "score", "confidence"),
        ),
        AlertAlgorithmSpec(
            key="volatility_mean_reversion",
            name="Volatility Mean Reversion",
            catalog_ref="algorithm:54",
            builder=_build_volatility_mean_reversion,
            default_param={
                "volatility_window": 5,
                "baseline_window": 8,
                "high_threshold": 1.2,
                "low_threshold": 0.8,
                "confirmation_bars": 1,
            },
            param_normalizer=require_volatility_mean_reversion_param,
            description="Fade unusually high or low realized volatility back toward its local baseline.",
            param_schema=(
                {
                    "key": "volatility_window",
                    "label": "Volatility window",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Lookback used for realized volatility.",
                },
                {
                    "key": "baseline_window",
                    "label": "Baseline window",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Lookback used for the volatility baseline average.",
                },
                {
                    "key": "high_threshold",
                    "label": "High threshold",
                    "type": "number",
                    "required": True,
                    "minimum": 0.0,
                    "description": "Volatility ratio above which volatility is considered elevated.",
                },
                {
                    "key": "low_threshold",
                    "label": "Low threshold",
                    "type": "number",
                    "required": True,
                    "minimum": 0.0,
                    "description": "Volatility ratio below which volatility is considered depressed.",
                },
                {
                    "key": "confirmation_bars",
                    "label": "Confirmation bars",
                    "type": "integer",
                    "required": True,
                    "minimum": 1,
                    "description": "Consecutive ratio extremes required before confirmation.",
                },
            ),
            tags=("volatility", "mean-reversion", "realized-vol"),
            category="volatility_options",
            family="volatility_options",
            subcategory="volatility",
            warmup_period=13,
            output_modes=("signal", "score", "confidence"),
        ),
        AlertAlgorithmSpec(
            key="delta_neutral_volatility_trading",
            name="Delta-Neutral Volatility Trading",
            catalog_ref="algorithm:55",
            builder=build_delta_neutral_volatility_trading_algorithm,
            default_param={
                "rows": [],
                "iv_rv_threshold": 0.05,
                "min_gamma": 0.0,
                "target_delta_band": 0.1,
            },
            param_normalizer=require_delta_neutral_volatility_trading_param,
            description="Trade IV-RV dislocations while targeting delta neutrality and tracking hedge demand.",
            param_schema=(
                {
                    "key": "rows",
                    "label": "Options rows",
                    "type": "array",
                    "required": True,
                    "description": "Options-surface input rows with symbol and ts fields.",
                },
                {
                    "key": "iv_rv_threshold",
                    "label": "IV-RV threshold",
                    "type": "number",
                    "required": True,
                    "minimum": 0.0,
                    "description": "Absolute IV minus realized-volatility gap required to activate a trade.",
                },
                {
                    "key": "min_gamma",
                    "label": "Minimum gamma",
                    "type": "number",
                    "required": True,
                    "minimum": 0.0,
                    "description": "Minimum net gamma required for the selected option structure.",
                },
                {
                    "key": "target_delta_band",
                    "label": "Target delta band",
                    "type": "number",
                    "required": True,
                    "minimum": 0.0,
                    "description": "Maximum absolute net delta allowed before re-hedging is required.",
                },
            ),
            tags=("options", "volatility", "delta-neutral"),
            category="volatility_options",
            family="volatility_options",
            subcategory="delta",
            warmup_period=2,
            input_domains=("options_chain", "underlying_price_series"),
            output_modes=("volatility_position", "greek_diagnostics", "diagnostics"),
        ),
        AlertAlgorithmSpec(
            key="gamma_scalping",
            name="Gamma Scalping",
            catalog_ref="algorithm:56",
            builder=build_gamma_scalping_algorithm,
            default_param={
                "rows": [],
                "rebalance_band": 0.1,
                "min_gamma": 0.0,
                "scalp_threshold": 0.01,
            },
            param_normalizer=require_gamma_scalping_param,
            description="Trigger hedge actions when a gamma-rich position drifts outside its delta band on large expected moves.",
            param_schema=(
                {
                    "key": "rows",
                    "label": "Options rows",
                    "type": "array",
                    "required": True,
                    "description": "Options-surface input rows with symbol and ts fields.",
                },
                {
                    "key": "rebalance_band",
                    "label": "Rebalance band",
                    "type": "number",
                    "required": True,
                    "minimum": 0.0,
                    "description": "Absolute delta band tolerated before a hedge rebalance is flagged.",
                },
                {
                    "key": "min_gamma",
                    "label": "Minimum gamma",
                    "type": "number",
                    "required": True,
                    "minimum": 0.0,
                    "description": "Minimum gamma required before scalping signals are considered valid.",
                },
                {
                    "key": "scalp_threshold",
                    "label": "Scalp threshold",
                    "type": "number",
                    "required": True,
                    "minimum": 0.0,
                    "description": "Minimum expected-versus-priced move gap required before re-hedging is worthwhile.",
                },
            ),
            tags=("options", "gamma", "scalping"),
            category="volatility_options",
            family="volatility_options",
            subcategory="gamma",
            warmup_period=2,
            input_domains=("options_chain", "underlying_price_series"),
            output_modes=("volatility_position", "greek_diagnostics", "diagnostics"),
        ),
        AlertAlgorithmSpec(
            key="volatility_risk_premium_capture",
            name="Volatility Risk Premium Capture",
            catalog_ref="algorithm:57",
            builder=build_volatility_risk_premium_capture_algorithm,
            default_param={
                "rows": [],
                "premium_threshold": 0.05,
                "policy": "short_vol",
            },
            param_normalizer=require_volatility_risk_premium_capture_param,
            description="Express long- or short-volatility positions from the implied-versus-realized volatility gap.",
            param_schema=(
                {
                    "key": "rows",
                    "label": "Options rows",
                    "type": "array",
                    "required": True,
                    "description": "Options-surface input rows with symbol and ts fields.",
                },
                {
                    "key": "premium_threshold",
                    "label": "Premium threshold",
                    "type": "number",
                    "required": True,
                    "minimum": 0.0,
                    "description": "Absolute IV-RV premium required before taking a volatility stance.",
                },
                {
                    "key": "policy",
                    "label": "Policy",
                    "type": "string",
                    "required": True,
                    "description": "Preferred policy for mapping the premium into long-vol or short-vol actions.",
                },
            ),
            tags=("options", "volatility", "premium"),
            category="volatility_options",
            family="volatility_options",
            subcategory="volatility",
            warmup_period=2,
            input_domains=("options_chain", "underlying_price_series"),
            output_modes=("volatility_position", "greek_diagnostics", "diagnostics"),
        ),
        AlertAlgorithmSpec(
            key="dispersion_trading",
            name="Dispersion Trading",
            catalog_ref="algorithm:58",
            builder=build_dispersion_trading_algorithm,
            default_param={"rows": [], "entry_threshold": 0.02},
            param_normalizer=require_dispersion_trading_param,
            description="Compare index implied volatility with constituent-implied volatility to express a dispersion view.",
            param_schema=(
                {
                    "key": "rows",
                    "label": "Options rows",
                    "type": "array",
                    "required": True,
                    "description": "Options-surface input rows with symbol and ts fields.",
                },
                {
                    "key": "entry_threshold",
                    "label": "Entry threshold",
                    "type": "number",
                    "required": True,
                    "minimum": 0.0,
                    "description": "Minimum dispersion gap magnitude required before a trade is signaled.",
                },
            ),
            tags=("options", "dispersion", "correlation"),
            category="volatility_options",
            family="volatility_options",
            subcategory="dispersion",
            warmup_period=2,
            input_domains=("options_chain", "underlying_price_series"),
            output_modes=("volatility_position", "greek_diagnostics", "diagnostics"),
        ),
        AlertAlgorithmSpec(
            key="skew_trading",
            name="Skew Trading",
            catalog_ref="algorithm:59",
            builder=build_skew_trading_algorithm,
            default_param={"rows": [], "entry_threshold": 0.02},
            param_normalizer=require_skew_trading_param,
            description="Trade relative richness in downside versus upside implied volatility.",
            param_schema=(
                {
                    "key": "rows",
                    "label": "Options rows",
                    "type": "array",
                    "required": True,
                    "description": "Options-surface input rows with symbol and ts fields.",
                },
                {
                    "key": "entry_threshold",
                    "label": "Entry threshold",
                    "type": "number",
                    "required": True,
                    "minimum": 0.0,
                    "description": "Minimum skew magnitude required before a skew trade is signaled.",
                },
            ),
            tags=("options", "skew", "surface"),
            category="volatility_options",
            family="volatility_options",
            subcategory="skew",
            warmup_period=2,
            input_domains=("options_chain", "underlying_price_series"),
            output_modes=("volatility_position", "greek_diagnostics", "diagnostics"),
        ),
        AlertAlgorithmSpec(
            key="term_structure_trading",
            name="Term Structure Trading",
            catalog_ref="algorithm:60",
            builder=build_term_structure_trading_algorithm,
            default_param={"rows": [], "entry_threshold": 0.02},
            param_normalizer=require_term_structure_trading_param,
            description="Trade unusually steep, flat, or inverted implied-volatility term structures.",
            param_schema=(
                {
                    "key": "rows",
                    "label": "Options rows",
                    "type": "array",
                    "required": True,
                    "description": "Options-surface input rows with symbol and ts fields.",
                },
                {
                    "key": "entry_threshold",
                    "label": "Entry threshold",
                    "type": "number",
                    "required": True,
                    "minimum": 0.0,
                    "description": "Minimum term-structure slope magnitude required before a trade is signaled.",
                },
            ),
            tags=("options", "term-structure", "surface"),
            category="volatility_options",
            family="volatility_options",
            subcategory="term",
            warmup_period=2,
            input_domains=("options_chain", "underlying_price_series"),
            output_modes=("volatility_position", "greek_diagnostics", "diagnostics"),
        ),
        AlertAlgorithmSpec(
            key="straddle_breakout_timing",
            name="Straddle Breakout Timing",
            catalog_ref="algorithm:61",
            builder=build_straddle_breakout_timing_algorithm,
            default_param={"rows": [], "move_threshold": 0.01},
            param_normalizer=require_straddle_breakout_timing_param,
            description="Time long-volatility straddle entries when expected movement exceeds priced movement.",
            param_schema=(
                {
                    "key": "rows",
                    "label": "Options rows",
                    "type": "array",
                    "required": True,
                    "description": "Options-surface input rows with symbol and ts fields.",
                },
                {
                    "key": "move_threshold",
                    "label": "Move threshold",
                    "type": "number",
                    "required": True,
                    "minimum": 0.0,
                    "description": "Minimum expected-versus-priced move gap required before buying volatility.",
                },
            ),
            tags=("options", "straddle", "breakout"),
            category="volatility_options",
            family="volatility_options",
            subcategory="straddle",
            warmup_period=2,
            input_domains=("options_chain", "underlying_price_series"),
            output_modes=("volatility_position", "greek_diagnostics", "diagnostics"),
        ),
    ]
    for spec in specs:
        register_algorithm(spec)
